name: FastAPI CI - Latest Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "Nguyen@1997"
          MYSQL_DATABASE: user_post

        ports:
          - 3308:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -P 3306 --silent && break
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run code format checks
      run: |
        black --check .
        isort --check-only .
        flake8 .

    - name: Run tests with coverage
      env:
        DATABASE_URL: mysql+pymysql://root:Nguyen%401997@127.0.0.1:3306/test_user_post
      run: |
        pytest --cov=.
