name: FastAPI CI - Latest Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi[all]
        pip install sqlalchemy==2.0.41
        pip install pymysql
        pip install python-jose[cryptography]
        pip install passlib[bcrypt]
        pip install pytest pytest-cov flake8 black isort mypy alembic

    - name: Run code format checks
      run: |
        black --check .
        isort --check-only .
        flake8 .

    - name: Run tests with coverage
      run: |
        pytest --cov=.

